<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.18362.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\magic-wand.ico</ApplicationIcon>
    <StartupObject>MultiWiz.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="gear.png" />
    <None Remove="gear.svg" />
    <None Remove="magic-wand.ico" />
    <None Remove="play-button-arrowhead.png" />
    <None Remove="plus.png" />
    <None Remove="trash-can.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\magic-wand.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InputSimulatorEx" Version="2.1.1" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NuGet.CommandLine" Version="6.8.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ShowMeTheXAML.MSBuild" Version="2.0.0" />
    <PackageReference Include="squirrel.windows" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="gear.png" />
    <Resource Include="gear.svg" />
    <Resource Include="magic-wand.ico" />
    <Resource Include="play-button-arrowhead.png" />
    <Resource Include="plus.png" />
    <Resource Include="trash-can.png" />
  </ItemGroup>

	<PropertyGroup>
		<NugetTools>$(PkgNuGet_CommandLine)\tools</NugetTools>
		<SquirrelTools>$(Pkgsquirrel_windows)\tools</SquirrelTools>

		<Version>1.0.0</Version>

		<NuspecFile>$(SolutionDir)MultiWiz\MultiWiz.nuspec</NuspecFile>
	</PropertyGroup>

	<Target Name="GenerateRelease" AfterTargets="AfterBuild" Condition="$(Configuration) == Release">
		<XmlPeek XmlInputPath="$(NuspecFile)" Query="/package/metadata/id/text()">
			<Output TaskParameter="Result" ItemName="ID" />
		</XmlPeek>

		<Exec Command="$(NugetTools)\NuGet.exe pack $(NuspecFile) -Version $(Version) -Properties Configuration=Release -OutputDirectory $(SolutionDir)Deployment\GeneratedNugets" />

		<Exec Command="$(SquirrelTools)\Squirrel.exe --releasify $(SolutionDir)Deployment\GeneratedNugets\@(ID).$(Version).nupkg --releaseDir=$(SolutionDir)Deployment\Releases" />
	</Target>

</Project>
