<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>magic-wand.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="gear.png" />
    <None Remove="gear.svg" />
    <None Remove="magic-wand.ico" />
    <None Remove="play-button-arrowhead.png" />
    <None Remove="plus.png" />
    <None Remove="trash-can.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="magic-wand.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InputSimulatorEx" Version="2.1.1" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ShowMeTheXAML.MSBuild" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="gear.png" />
    <Resource Include="gear.svg" />
    <Resource Include="magic-wand.ico" />
    <Resource Include="play-button-arrowhead.png" />
    <Resource Include="plus.png" />
    <Resource Include="trash-can.png" />
  </ItemGroup>

</Project>
